# Generated by Django 5.0.6 on 2024-06-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_emergency_base_remove_reg_base_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency_base',
            old_name='address_local',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='emergency_base',
            old_name='contact_local',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='emergency_base',
            old_name='name_local',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='emergency_base',
            old_name='relation_local',
            new_name='relation',
        ),
    ]
