# Generated by Django 5.0.6 on 2024-06-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0004_rename_address_local_emergency_base_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_base',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reg_base',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reg_base',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
