# Generated by Django 5.0.6 on 2024-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_alter_reg_base_blood_group_alter_reg_base_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_base',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
