# Generated by Django 5.0.6 on 2024-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_reg_base_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_base',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'Ab Positive'), ('AB-', 'Ab Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], default='A+', max_length=3),
        ),
    ]
