# Generated by Django 5.0.6 on 2024-06-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0008_alter_reg_base_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_base',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NA', 'Na')], default='F', max_length=3),
        ),
    ]
