# Generated by Django 5.0.6 on 2024-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medcine_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='morning_time',
            field=models.CharField(choices=[('morn', 'Morn'), ('eve', 'Eve')], default='morn', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medcines',
            field=models.ManyToManyField(related_name='appointments', to='docui.medicine'),
        ),
    ]
