# Generated by Django 5.0.6 on 2024-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0004_remove_appointment_medicines_medicineschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='morning_time',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='morning',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=100),
        ),
    ]
