# Generated by Django 5.0.6 on 2024-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0005_alter_appointment_morning_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='morning_time',
            field=models.CharField(choices=[('before meal', 'Before'), ('after meal', 'After')], default='after meal', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='afternoon',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='evening',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='night',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=100),
        ),
    ]
