# Generated by Django 5.0.6 on 2024-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0006_alter_appointment_morning_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='morning_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='refer_back',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
    ]
