# Generated by Django 5.0.6 on 2024-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0011_alter_medicineschedule_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineschedule',
            name='after',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='before',
            field=models.BooleanField(default=False),
        ),
    ]
