# Generated by Django 5.0.6 on 2024-06-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0012_medicineschedule_after_medicineschedule_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineschedule',
            old_name='after',
            new_name='aft',
        ),
        migrations.RemoveField(
            model_name='medicineschedule',
            name='before',
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='bef',
            field=models.BooleanField(default=False),
        ),
    ]
