# Generated by Django 5.0.6 on 2024-06-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0013_rename_after_medicineschedule_aft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='refer_back_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
