# Generated by Django 5.0.6 on 2024-06-30 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0014_appointment_refer_back_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('date_to_be_done', models.DateField(blank=True, null=True)),
                ('additional_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='docui.tests')),
            ],
        ),
    ]
