# Generated by Django 5.0.6 on 2024-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('doctors_assesment', models.CharField(max_length=200)),
                ('medcine_name', models.CharField(max_length=100)),
                ('morning_time', models.CharField(choices=[('morn', 'Morn'), ('eve', 'Eve')], max_length=100)),
            ],
        ),
    ]
