# Generated by Django 5.0.6 on 2024-06-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0003_rename_medcines_appointment_medicines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medicines',
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('morning', models.CharField(blank=True, max_length=100, null=True)),
                ('afternoon', models.CharField(blank=True, max_length=100, null=True)),
                ('evening', models.CharField(blank=True, max_length=100, null=True)),
                ('night', models.CharField(blank=True, max_length=100, null=True)),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docui.appointment')),
            ],
        ),
        migrations.DeleteModel(
            name='AppointmentMedicine',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
