# Generated by Django 5.0.6 on 2024-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0007_remove_appointment_morning_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineschedule',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
