# Generated by Django 5.0.6 on 2024-06-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0008_alter_medicineschedule_morning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineschedule',
            name='afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
