# Generated by Django 5.0.6 on 2024-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0009_alter_medicineschedule_afternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineschedule',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
