# Generated by Django 5.0.6 on 2024-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docui', '0010_alter_medicineschedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineschedule',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
